version: "3"
services:
  # DB administration :
  #     Find your bridge network interface with ifconfig, connect to its gateway (IP like 172.XX.0.1 or 172.XX.1.254)
  #     with the following port (like http://172.17.0.1:12180), log in to host mariadb, user `root`,
  #     password is the MARIADB_ROOT_PASSWORD above
  # Reverse proxy setup :
  #     Proxy pass to http://<gateway>:<port>, port is defined just below,
  #     gateway is the same address as above (172.XX.0.1)
  plsres-website:
    image: plstek/plsres-website
    build: https://github.com/PLStek/PLSres-docker.git
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - MYSQL_HOST=plsres-db
      - MYSQL_DBNAME=plsres    # Create the DB through adminer
      - MYSQL_USERNAME=plsres  # Create the user and give it privileges on the DB through adminer
      - MYSQL_PASSWORD=        # Set this : password for the `plsres` user created through adminer

  plsres-db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD= # Set this : `root` user password for the DB server, to log into adminer

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "12180:8080"
