version: "3"
services:
  # Reverse proxy setup :
  #     Proxy pass to http://<gateway>:<port>, port is defined just below,
  #     gateway is the same address as above (172.XX.0.1)
  plsres-website:
    image: plstek/plsres-website
    build: https://github.com/PLStek/PLSres-docker.git
    ports:
      - "12038:80"
    restart: unless-stopped
    depends_on:
      - plsres-db
    environment:
      - MARIADB_HOST=plsres-db
      - MARIADB_DBNAME=plsres         # DB name (= MARIADB_DATABASE in plsres-db)
      - MARIADB_USER=plsres           # User name (= MARIADB_USER in plsres-db)
      - MARIADB_PASSWORD=REPLACE_THIS # Password for `plsres` (= MARIADB_PASSWORD in plsres-db)

  plsres-db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_USER=plsres
      - MARIADB_DATABASE=plsres
      - MARIADB_PASSWORD=REPLACE_THIS      # Set this : app user password
      - MARIADB_ROOT_PASSWORD=REPLACE_THIS # Set this : admin user and password for the DB server, to log into adminer
    volumes:
      - ./plsres-db:/var/lib/mysql         # External Docker volume to backup

  plsres-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "12171:8080"
